### PR TITLE
Added .cache folder (created by parcel) to ignore

### PR DESCRIPTION
**Pull request by mattlockyer**

### CODE REVIEW

**Comment by icerove** [comment]
We have two ignore file and after generating new project, the .gitignore file will disappear and near.gitignore file will become .gitignore, could you touch this more to make all the necessary ignore into one file?

**Comment by icerove** [comment]
see #127

**Comment by mattlockyer** [comment]
Thanks for the review. Did not know the build structure, this is good to know for the future!

**Comment by chadoh** [comment]
Are the errors on `master` being looked into by anyone? cc @janedegtiareva @icerove

**Comment by mattlockyer** [comment]
@icerove bumping this w/ https://github.com/near/create-near-app/pull/331/commits/e412e2e305d8aa87c2ff1a06f52ef84e32b341c2

**Pull request merged**
