### PR TITLE
Rust installation instructions

### PR DESCRIPTION
**Pull request by janedegtiareva**

### CODE REVIEW

**Comment by mikedotexe** [comment]
The square brackets show up
Screenshot 2020-06-26 14 12 08

**Comment by vgrichina** [comment]
I think we also need to automate this in future:
https://github.com/near/create-near-app/issues/374

**Comment by amgando** [comment]
@janedegtiareva can you fix conflicting files here?

**Comment by janedegtiareva** [comment]
This will get added to https://github.com/near/create-near-app/pull/389 to minimize merge conflicts

**Pull request closed without merging**
